// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gegivbvvfosypeiobkil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZ2l2YnZ2Zm9zeXBlaW9ia2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3OTc4MjIsImV4cCI6MjA3NDM3MzgyMn0.Hj2L3iFL40-akbM8Kp2yzJmVlBzovgaIBgu2zBI8Tq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});